baseURL = 'https://pvutov.com'
languageCode = 'en-us'
defaultContentLanguage = 'bg'
title = 'Charmella Wellness Studio'

theme = 'hugo-universal-theme'

# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6

[[menu.main]]
    name       = "Ценоразпис"
    identifier = "menu.pricing"
    url        = "/pricing"
    weight     = 3

[[menu.main]]
    name       = "Контакти"
    identifier = "menu.Kontakti"
    url        = "/contact"
    weight     = 2

[[menu.main]]
    name       = "Начало"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[params.testimonials]
    enable = true
    title = "Отзиви"
    subtitle = "Още отзиви може да видите на https://studio24.bg/charmella-s8986"

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000


[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Свържете се с нас на 0877 72 79 83 или
0878 54 94 50.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+359 877 72 79 83" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:charmellamassagestudio@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
#    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/mbjvwewp"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "Ние сме масажни терапевти с многогодишен опит."
    copyright = "Copyright (c) 2023, Масажно Студио Charmella"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Charmella Logo"

    # logo = "img/logo-large-rect.jpg"
    logo = "img/logo-square.jpg"
    logo_small = "img/logo-square.jpg"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Charmella</strong>
        <br>ул. Солун 56,
        <br>бл.2, партер, вътрешен двор, до Ветрило
        <br>1680 Борово
        <br>София
      </p>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1466.7676410776867!2d23.288912422585135!3d42.67120239767433!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa851a4e0766cb%3A0x9fc8cdbcc78cbc1d!2sCharmella%20massage%20studio!5e0!3m2!1sen!2sch!4v1698598411516!5m2!1sen!2sch" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      """

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+359 877 72 79 83"
    pre = "<i class='fas fa-2x fa-phone'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fab fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:charmellamassagestudio@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
